import type { Metadata } from "next"
import DebouchageClientPage from "./DebouchageClientPage"

export const metadata: Metadata = {
  title: "Services de Débouchage de Canalisations | Intervention Rapide 24/7",
  description:
    "Services professionnels de débouchage de canalisations, WC, éviers et douches. Intervention rapide 24/7, équipement spécialisé et garantie de satisfaction.",
  keywords: [
    "Débouchage curatif canalisation",
    "Débouchage préventif canalisation",
    "Débouchage domestique",
    "Débouchage industriel",
    "Débouchage canalisation Bruxelles",
    "Débouchage canalisation",
    "Tarif débouchage canalisation",
    "Prix débouchage canalisation",
    "Urgence débouchage canalisation",
    "Débouchage canalisation 24/7",
    "Nettoyage haute pression canalisation",
    "Entretien canalisation",
    "Inspection vidéo des égouts",
    "Vidange fosse septique",
    "Réparation de canalisation",
    "Débouchage évier",
    "Débouchage haute pression",
    "Débouchage égouts",
    "Débouchage cuisine",
    "Débouchage salle de bain",
    "Débouchage WC",
    "Débouchage douche",
    "Débouchage baignoire",
    "Débouchage tuyaux",
    "Débouchage canalisation bouchée",
    "Débouchage canalisation rapide",
    "Débouchage canalisation pas cher",
    "Entreprise de débouchage",
    "Service de débouchage",
    "Déboucheur professionnel",
    "Assainissement de canalisations",
    "Curage de canalisations",
    "Inspection caméra des canalisations",
    "Dépannage de canalisations",
    "Débouchage chambre de visite",
    "Débouchage sterput",
    "Débouchage avaloir",
    "Débouchage canalisation cuisine professionnelle",
    "Débouchage canalisation bâtiment industriel",
    "Débouchage canalisation immeuble",
    "Débouchage collecteur d'égout",
    "Débouchage colonne d'immeuble",
    "Débouchage tuyau de descente d'eau pluviale",
    "Débouchage drain de fondation",
    "Corniche bouché",
    "Débouchage canalisation restaurant",
    "Débouchage industriel",
    "Débouchage commercial",
    "Débouchage institutionnel",
    "Débouchage urgence 24/7",
    "Débouchage haute pression",
    "Débouchage caméra inspection",
    "Débouchage tuyauterie industrielle",
    "Débouchage égouts commerciaux",
    "Débouchage canalisations collectives",
    "Débouchage parking souterrain",
    "Débouchage station de pompage",
    "Débouchage séparateur d'hydrocarbures",
    "Débouchage bâtiment industriel",
    "Débouchage entrepôt",
    "Débouchage usine",
    "Débouchage centre commercial",
    "Débouchage hôpital",
    "Débouchage école",
    "Débouchage immeuble à bureaux",
    "Débouchage copropriété",
    "Débouchage restaurant",
    "Débouchage hôtel",
    "Débouchage garage",
    "Débouchage station-service",
    "Débouchage aéroport",
    "Débouchage port maritime",
    "Débouchage chantier de construction",
    "Contrat entretien canalisations",
    "Maintenance préventive canalisations",
    "Diagnostic canalisations",
    "Rapport inspection canalisations",
    "Devis gratuit débouchage",
    "Tarif débouchage entreprise",
    "Prix débouchage industriel",
    "Service client dédié",
    "Technicien certifié",
    "Équipement spécialisé",
    "Intervention rapide",
    "Résolution de problèmes complexes",
    "Solution durable",
    "Garantie satisfaction",
    "Débouchage siphon",
    "Débouchage urgent",
    "Débouchage camion pompe",
    "Débouchage fosse septique",
    "Débouchage citerne d'eau de pluie",
    "Débouchage canalisation extérieure",
    "Débouchage égouttage",
    "Débouchage broyeur WC",
    "Débouchage canalisation cuisine professionnelle",
    "Débouchage canalisation bâtiment industriel",
    "Débouchage canalisation immeuble",
    "Débouchage collecteur d'égout",
    "Débouchage colonne d'immeuble",
    "Débouchage tuyau de descente d'eau pluviale",
    "Débouchage drain de fondation",
  ],
}

export default function DebouchagePage() {
  return <DebouchageClientPage />
}
